
INSERT INTO PLAYERS (name) VALUES ('леша');
INSERT INTO PLAYERS (name) VALUES ('маша');
INSERT INTO PLAYERS (name) VALUES ('ваня');
INSERT INTO PLAYERS (name) VALUES ('лена');
INSERT INTO PLAYERS (name) VALUES ('дима');
INSERT INTO PLAYERS (name) VALUES ('олег');
INSERT INTO PLAYERS (name) VALUES ('катя');
INSERT INTO PLAYERS (name) VALUES ('сергей');
INSERT INTO PLAYERS (name) VALUES ('настя');
INSERT INTO PLAYERS (name) VALUES ('павел');


INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (1, 2, 1);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (3, 4, 4);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (1, 5, 5);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (2, 3, 2);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (4, 5, 4);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (1, 3, 3);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (2, 5, 2);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (1, 4, 1);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (3, 5, 5);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (2, 4, 4);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (6, 7, 6);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (8, 9, 9);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (10, 1, 10);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (2, 6, 2);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (3, 7, 3);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (4, 8, 4);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (5, 9, 9);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (6, 10, 10);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (7, 8, 7);
INSERT INTO MATCHES (PLAYER1_ID, PLAYER2_ID, WINNER_ID) VALUES (1, 9, 1);